export const ROUTES = {
  HOME: "/",
  INVITE: "/invites/:code",
  LOGIN: "/login",
  REGISTER: "/register",
  CHATS: "chats",
  CONTACT: "contacts",
  PROFILE: "profile",
  PRIVACY: "privacy",
  ABOUT: "about",
  PLANS: "plans",
  HELPANDSUPPORT: "help",
  CONVERSATION_ID: ":conversationId",
  DASHBOARD: "/dashboard",
  ACCOUNTS: "/accounts",
  AUTH_CALLBACK: "/auth/callback",
} as const;
